[pytest]
# Only look inside the tests/ folder
testpaths= tests

# Only files starting with test_ are tests
python_files =test_*.py

# Verbose output
addopts = -v --strict-markers

# Registered test markers
markers = 
    slow: marks slow tests,  heavy tests
    auth: authentication tests
    business: business logic tests

